### ISSUE TITLE
TODO-List for portingoriginal UI to Quasar

### ISSUE THREAD

**Issue by H256** [H256/gekko#1]
### Todo:
- [ ]  convert base assets etc. to quasar
- [ ] revamp ajax and store module with axios
- [x] convert **config-pages** to quasar
- [x] convert **data-pages** to quasar
- [ ] convert **backtester-pages** to quasar
- [ ] convert **live-gekko-pages** to quasar
- [ ] add liveview of running imports into sidebar or top toolbar
- [ ] get rid of global moment dependency
- [ ] get rid of global humanize-duration dependency
- [ ] get rid of custom ajax dependency
- [ ] try to build backtest graph with plotly.js instead of d3 custom plot
