### ISSUE TITLE
TODO: Enhancement ideas

### ISSUE THREAD

**Issue by H256** [H256/gekko#2]
### Todo:
- [ ] add dashboard overview for all running processes (imports, live-gekkos, backtest)
- [ ] add liveview of running imports into sidebar or top toolbar
- [ ] try to build backtest graph with plotly.js instead of d3 custom plot
